# Generated by Django 4.2.1 on 2023-06-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audiofile', models.FileField(upload_to='songs/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumTitle', models.CharField(max_length=100)),
                ('albumArtist', models.CharField(max_length=100)),
                ('albumYear', models.IntegerField()),
                ('albumGenre', models.CharField(max_length=100)),
                ('albumImage', models.ImageField(upload_to='images/')),
                ('songslist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.song')),
            ],
        ),
    ]
