# Generated by Django 4.2.1 on 2023-07-04 19:18

from django.db import migrations, models
import main.validator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_delete_user_rename_songslist_album_songlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='songlist',
        ),
        migrations.AlterField(
            model_name='song',
            name='audiofile',
            field=models.FileField(upload_to='songs/', validators=[main.validator.validate_is_mp3]),
        ),
        migrations.AddField(
            model_name='album',
            name='songlist',
            field=models.ManyToManyField(related_name='+', to='main.song'),
        ),
    ]
