# Generated by Django 4.2.1 on 2023-07-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_song_options_remove_album_songlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songlist',
            field=models.ManyToManyField(null=True, related_name='+', to='main.song'),
        ),
    ]
