# Generated by Django 4.2.1 on 2023-07-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_album_songlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songlist',
            field=models.ManyToManyField(blank=True, related_name='+', to='main.song'),
        ),
    ]
